### PR TITLE
Zig CC cross-compilation support for Windows on Linux host.

### PR DESCRIPTION
**Pull request by svladykin**
Was able to cross-compile everything on Linux for Windows with Zig. Some minor cleanup was needed.

It would be great to add a CI check for that. Here is the script:

```
export ZIG=zig-linux-x86_64-0.12.0-dev.1834+f36ac227b
rm -rf build && mkdir build && cd build
curl -o zig.tar.xz "https://ziglang.org/builds/$ZIG.tar.xz"
tar -xf zig.tar.xz
export CC="$(pwd)/$ZIG/zig cc -target x86_64-windows"
cmake -DCMAKE_SYSTEM_NAME=Windows ..
make
```

### CODE REVIEW

**Comment by tezc** [comment]
To add it to CI, we should setup Linux for Windows first right? If you already know how to do it, you can add a job to windows.yml. Otherwise, let's handle it later.

**Comment by svladykin** [comment]
It actually can be executed on any Linux. Let me try to add it to `.ubuntu.yml`.

**Comment by svladykin** [comment]
Checked the build log for `x64-ubuntu / Zig Windows`, it works as expected.

**Comment by tezc** [comment]
thank you

**Pull request merged**
