### PR TITLE
Build test on debug only

### PR DESCRIPTION
**Pull request by tezc**

### CODE REVIEW

**Comment by rafaeldelboni** [comment]
Still getting some warnings on sc_threads
```bash
/home/delboni/Workspace/c/sc/thread/sc_thread.c: In function ‘sc_thread_start’:
/home/delboni/Workspace/c/sc/thread/sc_thread.c:127:9: error: ‘strncpy’ specified bound 128 equals destination size [-Werror=stringop-truncation]
  127 |         strncpy(thread->err, strerror(rc), sizeof(thread->err));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/delboni/Workspace/c/sc/thread/sc_thread.c:118:9: error: ‘strncpy’ specified bound 128 equals destination size [-Werror=stringop-truncation]
  118 |         strncpy(thread->err, strerror(rc), sizeof(thread->err));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 79%] Built target sc_option
[ 79%] Built target sc_heap
/home/delboni/Workspace/c/sc/thread/sc_thread.c: In function ‘sc_thread_join’:
/home/delboni/Workspace/c/sc/thread/sc_thread.c:147:9: error: ‘strncpy’ specified bound 128 equals destination size [-Werror=stringop-truncation]
  147 |         strncpy(thread->err, strerror(rc), sizeof(thread->err));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by rafaeldelboni** [comment]
Just add `- 1` at the end of those lines:
```c
        strncpy(thread->err, strerror(rc), sizeof(thread->err) - 1);
```

**Comment by rafaeldelboni** [comment]
You missed line 147 `sc/thread/sc_thread.c:147` :)

**Comment by tezc** [comment]
wow, my gcc & clang don't complain about that. Probably I and CI have older versions, I'll add newer versions to CI.

**Comment by rafaeldelboni** [comment]
I usually have to clean the build folder or make a different one for release and debug to have these warnings showing on haha

Thanks, is working fine now!

closes #44

**Review by rafaeldelboni — APPROVED** [review]

**Comment by rafaeldelboni** [comment]
closes #44

**Review by rafaeldelboni — APPROVED** [review]
closes #44

**Comment by tezc** [comment]
Thanks a lot for issue & review

**Pull request merged**
